apiVersion: v1
kind: ConfigMap
metadata:
  name: empattendance-config
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "empattendance.labels" . | indent 4 }}
data:
  JAVA_OPTS: {{ .Values.configmap.javaOptions }}
  EXAMPLE_VAR: "THIS IS AN EXAMPLE VARIABLE"

  SPRING_KAFKA_BOOTSTRAPSERVERS: {{ include "kafka.service" . }}:9092

