apiVersion: v1
kind: ServiceAccount
metadata:
    name: empattendance
    namespace: {{ .Release.Namespace }}
    labels:
      app: empattendance
      service: empattendance
      {{- include "empattendance.labels" . | indent 6 }}
