spring:

  kafka:
    defaultConcurrency: 1
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: MYTOPIC1:MYPOJO1,MYTOPIC2:MYPOJO2


  datasource:
    platform: mysql
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/employee?autoreconnect=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

